In [2]:
import numpy as np
import pandas as pd
import wget
import datetime
import os
import matplotlib.pyplot as plt

In [3]:
"""
Buy Selling Maximize Profit subroutines
With numpy library calculations are over 15 times faster than classic approach
"""

def bsmp_numpy(prices):
    prices = np.asarray(prices)
    return np.max(prices - np.minimum.accumulate(prices))

def bsmp(prices):
    max_px = 0
    min_px = prices[0]
    for px in prices[1:]:
        min_px = min(min_px, px)
        max_px = max(px - min_px, max_px)
    return max_px

In [4]:
TICKER = "CDR"
START_DATE = "2018-01-01"
END_DATE = "2019-02-01"
FILENAME = "data.txt"

if os.path.exists(FILENAME):
    os.remove(FILENAME)

In [5]:
# grab file with stock data
url = "https://stooq.pl/q/d/l/?s={0}&d1={1}&d2={2}&i=d".format(TICKER, START_DATE.replace("-",""), END_DATE.replace("-",""))  
wget.download(url, FILENAME)

'data.txt'

In [6]:
df = pd.read_csv(FILENAME) # load data frame with data from CSV
df

           Data  Otwarcie  Najwyzszy  Najnizszy  Zamkniecie  Wolumen
0    2018-01-03      97.7     100.00      97.70       98.00   212199
1    2018-01-04      99.0      99.75      97.25       98.00   192525
2    2018-01-05      99.0      99.40      97.75       99.00   120812
3    2018-01-08      99.4     101.10      98.35      100.70   284250
4    2018-01-09     100.7     100.80      99.20      100.00   122877
5    2018-01-10      99.9      99.90      97.75       98.15   102408
6    2018-01-11      99.0     106.80      98.30      104.20   447301
7    2018-01-12     105.0     108.40     104.30      107.00   364636
8    2018-01-15     108.5     109.40     105.70      105.80   131011
9    2018-01-16     107.0     112.10     106.50      111.10   390235
10   2018-01-17     112.0     119.00     111.50      119.00   770193
11   2018-01-18     121.0     123.40     116.00      119.70   642804
12   2018-01-19     120.0     121.40     117.00      121.30   335162
13   2018-01-22     121.9     121.90     118.10      119.30   202318
14   2018-01-23     118.7     120.60     116.10      118.30   258942
15   2018-01-24     117.0     118.80     114.20      116.50   259783
16   2018-01-25     116.0     116.40     112.00      112.00   206717
17   2018-01-26     111.1     116.60     111.10      114.80   125625
18   2018-01-29     115.0     115.80     112.60      115.80    98301
19   2018-01-30     115.0     115.00     112.60      114.00    79089
20   2018-01-31     114.0     118.70     113.30      116.00   321184
21   2018-02-01     116.1     117.40     113.60      115.00   114568
22   2018-02-02     114.1     114.70     112.70      113.40   164583
23   2018-02-05     111.0     112.30     108.50      109.50   196752
24   2018-02-06     102.6     107.60     101.80      106.00   562601
25   2018-02-07     109.9     111.30     108.20      111.30   296436
26   2018-02-08     113.0     114.60     109.60      111.00   253372
27   2018-02-09     109.2     110.90     106.20      106.20   364186
28   2018-02-12     109.2     109.30     106.30      106.70   183269
29   2018-02-13     107.7     110.20     107.10      109.10   257193
..          ...       ...        ...        ...         ...      ...
234  2018-12-07     145.0     149.70     143.70      144.00   253762
235  2018-12-10     142.2     145.60     140.20      140.20   193384
236  2018-12-11     141.7     143.80     140.10      140.40   205858
237  2018-12-12     142.7     143.90     140.00      141.80   207650
238  2018-12-13     143.8     145.20     140.60      144.00   193353
239  2018-12-14     142.0     146.30     141.30      143.60   172980
240  2018-12-17     144.2     144.40     139.00      139.00   206396
241  2018-12-18     138.1     143.40     135.40      142.60   286163
242  2018-12-19     142.8     153.00     141.20      153.00   398828
243  2018-12-20     149.3     152.80     148.40      149.80   380857
244  2018-12-21     150.1     156.80     149.00      151.00   649369
245  2018-12-27     156.0     157.00     146.60      147.50   237923
246  2018-12-28     145.0     146.90     143.20      145.60   284736
247  2019-01-02     145.4     151.30     142.10      151.00   197015
248  2019-01-03     150.8     150.80     147.00      148.00   223586
249  2019-01-04     148.0     150.80     148.00      150.70   163950
250  2019-01-07     152.0     154.60     151.50      153.70   187987
251  2019-01-08     154.5     156.70     152.00      153.60   278310
252  2019-01-09     154.1     165.00     154.00      165.00   477150
253  2019-01-10     164.5     172.20     160.10      171.00   695069
254  2019-01-11     173.0     177.10     164.00      165.10   484480
255  2019-01-14     164.0     164.00     158.80      159.50   262026
256  2019-01-15     161.2     164.00     159.00      162.30   312692
257  2019-01-16     164.0     166.60     163.50      166.60   149840
258  2019-01-17     165.0     172.00     164.60      171.10   369086
259  2019-01-18     173.0     175.00     170.50      173.90   301796
260  2019-01-21     173.8     173.80     170.70      172.80   122117
261  2019-01-22     172.7     176.40     172.30      174.10   148452
262  2019-01-23     177.5     198.40     176.00      194.60  1224218
263  2019-01-24     194.8     201.40     186.00      190.00   779462

[264 rows x 6 columns]

In [7]:
prices = df['Zamkniecie']
nprices = np.array(prices.tolist())
nprices

array([ 98.  ,  98.  ,  99.  , 100.7 , 100.  ,  98.15, 104.2 , 107.  ,
       105.8 , 111.1 , 119.  , 119.7 , 121.3 , 119.3 , 118.3 , 116.5 ,
       112.  , 114.8 , 115.8 , 114.  , 116.  , 115.  , 113.4 , 109.5 ,
       106.  , 111.3 , 111.  , 106.2 , 106.7 , 109.1 , 108.9 , 108.9 ,
       110.8 , 109.  , 109.  , 109.5 , 109.7 , 108.6 , 106.9 , 107.6 ,
       107.  , 104.8 , 105.9 , 106.  , 103.6 , 109.8 , 108.2 , 109.5 ,
       114.5 , 114.3 , 114.6 , 113.5 , 109.2 , 109.3 , 109.8 , 112.9 ,
       112.  , 111.  , 109.  , 112.9 , 109.2 , 109.4 , 109.6 , 111.5 ,
       114.9 , 120.4 , 123.3 , 125.  , 124.7 , 123.7 , 122.1 , 119.3 ,
       120.  , 121.5 , 119.9 , 119.5 , 120.2 , 118.2 , 115.7 , 115.6 ,
       116.  , 124.8 , 124.8 , 124.9 , 128.  , 137.  , 144.9 , 144.9 ,
       145.  , 139.  , 139.8 , 145.  , 139.  , 140.  , 147.  , 146.5 ,
       144.6 , 144.7 , 144.7 , 145.  , 143.7 , 147.2 , 149.5 , 157.6 ,
       157.  , 152.6 , 153.  , 150.2 , 143.8 , 150.2 , 155.3 , 164.7 ,
       168.  , 172.  , 165.2 , 165.8 , 164.1 , 166.3 , 165.8 , 165.7 ,
       164.9 , 157.5 , 161.8 , 161.1 , 162.8 , 167.2 , 179.  , 176.7 ,
       175.8 , 178.  , 178.6 , 184.8 , 192.  , 197.4 , 201.2 , 209.8 ,
       203.  , 204.6 , 203.6 , 208.  , 210.2 , 214.4 , 217.6 , 214.6 ,
       197.5 , 205.  , 195.4 , 197.  , 198.7 , 205.6 , 214.8 , 214.4 ,
       203.  , 210.6 , 213.  , 206.6 , 203.2 , 210.  , 213.  , 206.2 ,
       209.  , 206.4 , 212.  , 219.2 , 219.8 , 210.4 , 206.  , 201.8 ,
       194.5 , 184.7 , 182.4 , 173.5 , 179.7 , 182.6 , 178.2 , 180.2 ,
       182.  , 181.2 , 189.5 , 189.9 , 189.7 , 193.7 , 187.4 , 186.8 ,
       187.1 , 192.4 , 187.3 , 192.9 , 190.  , 193.  , 180.3 , 182.3 ,
       163.1 , 164.  , 155.5 , 152.  , 163.  , 158.6 , 165.  , 164.5 ,
       155.  , 157.  , 157.  , 144.3 , 143.3 , 151.  , 142.9 , 148.2 ,
       152.4 , 158.3 , 164.3 , 162.1 , 163.3 , 165.2 , 156.  , 149.8 ,
       146.5 , 146.5 , 138.  , 132.4 , 134.  , 129.  , 137.5 , 139.  ,
       140.2 , 138.9 , 134.8 , 138.  , 141.  , 142.2 , 154.  , 154.1 ,
       148.4 , 143.7 , 144.  , 140.2 , 140.4 , 141.8 , 144.  , 143.6 ,
       139.  , 142.6 , 153.  , 149.8 , 151.  , 147.5 , 145.6 , 151.  ,
       148.  , 150.7 , 153.7 , 153.6 , 165.  , 171.  , 165.1 , 159.5 ,
       162.3 , 166.6 , 171.1 , 173.9 , 172.8 , 174.1 , 194.6 , 190.  ])

In [8]:
a = datetime.datetime.now()
for x in range(10000):
    bsmp_numpy(nprices)
b = datetime.datetime.now()
print "Total bsmp_numpy execution [msec]:" + str(int((b-a).total_seconds() * 1000))

Total [msec]:86

In [9]:
a = datetime.datetime.now()
for x in range(10000):
    bsmp(nprices)
b = datetime.datetime.now()
print "Total bsmp execution [msec]:" + str(int((b-a).total_seconds() * 1000))

Total [msec]:1561

In [ ]:
fig, ax = plt.subplots()
ax.plot(prices)
plt.show(block=True)